Repository Diogo-ss/42-header.nvim, pull requests merged in 2024-04, with the labels that each got.

#15 feat: add git support, rewrite part of the code, add new checking and CI and new error handling.
  .github/README.md
  .github/workflows/check.yml
  .github/workflows/ci.yml
  .github/workflows/format.yml
  lua/42header.lua
  lua/42header/config/init.lua
  lua/42header/utils/git.lua
  lua/42header/utils/header.lua
  lua/42header/utils/init.lua
Labels: documentation, enhancement, CI

#16 chore(main): release 2.0.0
  CHANGELOG.md
Labels: autorelease: pending

#17 feat(git): add support for includes in git config
  lua/42header/utils/git.lua
Labels: documentation

#18 chore(main): release 2.1.0
  CHANGELOG.md
Labels: autorelease: pending
